[CmdletBinding()]
param(
    [string]$SourceLab = "C:\Lab_Win11",
    [string]$PublishRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Section {
    param([string]$Title)
    Write-Host ""
    Write-Host ("=" * 72) -ForegroundColor DarkGray
    Write-Host $Title -ForegroundColor Cyan
    Write-Host ("=" * 72) -ForegroundColor DarkGray
}

function Assert-Path {
    param(
        [string]$Path,
        [string]$Name
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Name not found: $Path"
    }
}

if ([string]::IsNullOrWhiteSpace($PublishRoot)) {
    if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) {
        $PublishRoot = $PSScriptRoot
    } else {
        $PublishRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}

$SourceLab = (Resolve-Path -LiteralPath $SourceLab).Path.TrimEnd("\")
$PublishRoot = (Resolve-Path -LiteralPath $PublishRoot).Path.TrimEnd("\")

Assert-Path -Path $SourceLab -Name "Source lab"
Assert-Path -Path (Join-Path $SourceLab "start_lab.cmd") -Name "start_lab.cmd"

if ($PublishRoot -eq $SourceLab) {
    throw "PublishRoot must be different from SourceLab. Do not sync GitHub inside the production lab."
}

Write-Section "Lab Win11 GitHub sync"
Write-Host "Source : $SourceLab"
Write-Host "Publish: $PublishRoot"

$itemsToCopy = @(
    "Ayuda",
    "Herramientas",
    "start_lab.cmd",
    "LEEME.txt"
)

$excludes = @(
    ".git",
    ".gitignore",
    "Sync-GitHub-Lab.cmd",
    "Sync-GitHub-Lab.ps1",
    "README_GITHUB_SYNC.txt"
)

Write-Section "Cleaning old published files"
Get-ChildItem -Force -LiteralPath $PublishRoot |
    Where-Object { $_.Name -notin $excludes } |
    ForEach-Object {
        Write-Host "Removing $($_.Name)"
        Remove-Item -LiteralPath $_.FullName -Recurse -Force
    }

Write-Section "Copying public lab files"
foreach ($item in $itemsToCopy) {
    $source = Join-Path $SourceLab $item
    if (-not (Test-Path -LiteralPath $source)) {
        Write-Host "Skipping missing item: $item" -ForegroundColor Yellow
        continue
    }

    $destination = Join-Path $PublishRoot $item
    Write-Host "$item"
    Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
}

Write-Section "Writing .gitignore"
$gitignore = @'
# Lab working payload - keep folder skeleton, ignore real deployment payload
Trabajo/**
!Trabajo/
!Trabajo/README.md
!Trabajo/AnswerFiles/
!Trabajo/AnswerFiles/README.md
!Trabajo/Drivers/
!Trabajo/Drivers/README.md
!Trabajo/ISOs/
!Trabajo/ISOs/README.md
!Trabajo/Logs/
!Trabajo/Logs/README.md
!Trabajo/Mount/
!Trabajo/Mount/README.md
!Trabajo/Scratch/
!Trabajo/Scratch/README.md
!Trabajo/images/
!Trabajo/images/README.md
!Trabajo/offline/
!Trabajo/offline/README.md
!Trabajo/packages/
!Trabajo/packages/README.md

*.wim
*.esd
*.swm
*.iso
*.log
*.cab
*.msu
*.inf

# Local/user files
*.lnk
desktop.ini
Thumbs.db
*.tmp
*.bak

# Generated by local tests
__pycache__/
'@
[System.IO.File]::WriteAllText((Join-Path $PublishRoot ".gitignore"), $gitignore, [System.Text.UTF8Encoding]::new($false))

Write-Section "Writing GitHub folder skeleton"
$folderDocs = [ordered]@{
    "Trabajo" = @"
# Trabajo

Workspace used by the Windows 11 deployment lab.

Put real ISOs, WIM/ESD/SWM images, drivers, packages and logs here locally.
Heavy/private deployment payload is intentionally ignored by Git.
"@
    "Trabajo\images" = @"
# Trabajo\images

Put Windows image files here:

- boot.wim
- install.wim
- install.esd
- install.swm / install2.swm

Do not commit real image files to GitHub.
"@
    "Trabajo\ISOs" = @"
# Trabajo\ISOs

Put Windows ISO files here locally.

Do not commit ISO files to GitHub.
"@
    "Trabajo\Drivers" = @"
# Trabajo\Drivers

Put extracted INF drivers here.

The lab injects drivers recursively from this folder.
Do not commit real driver packs to GitHub unless you are sure they are redistributable.
"@
    "Trabajo\packages" = @"
# Trabajo\packages

Put CAB/MSU packages here for DISM package injection.

Do not commit update packages to GitHub.
"@
    "Trabajo\offline" = @"
# Trabajo\offline

Temporary DISM mount folder.

The assistant script removes this README before mounting.
Keep this folder empty when running manual DISM mount commands.
"@
    "Trabajo\Scratch" = @"
# Trabajo\Scratch

Temporary DISM scratch folder.

Logs and temporary files can be deleted when no DISM operation is running.
"@
    "Trabajo\Logs" = @"
# Trabajo\Logs

DISM and lab logs go here.

Logs are ignored by Git.
"@
    "Trabajo\Mount" = @"
# Trabajo\Mount

Spare mount/work folder for manual tests.
"@
    "Trabajo\AnswerFiles" = @"
# Trabajo\AnswerFiles

Optional location for unattend/autounattend XML files.

Do not commit files containing product keys, passwords or private company data.
"@
}

foreach ($entry in $folderDocs.GetEnumerator()) {
    $dir = Join-Path $PublishRoot $entry.Key
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    [System.IO.File]::WriteAllText((Join-Path $dir "README.md"), $entry.Value.Trim() + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

Write-Section "Writing README.md"
$readme = @'
# Lab Win11

Windows 11 deployment lab for preparing install images and USB media.

## Quick Start

1. Download or clone this repository.
2. Run `start_lab.cmd`.
3. Choose your language.
4. Put your working files under `Trabajo`:
   - `Trabajo\ISOs` for Windows ISO files
   - `Trabajo\images` for `boot.wim`, `install.wim`, `install.esd` or `install*.swm`
   - `Trabajo\Drivers` for extracted INF drivers
   - `Trabajo\packages` for CAB/MSU packages

The lab uses Windows PowerShell 5.1 and DISM.

## Important

Real deployment payload is intentionally ignored by Git:

- ISO files
- WIM/ESD/SWM images
- driver packs
- packages
- logs
- temporary mount contents

The repository contains the lab, not your private deployment payload.

## Publishing Workflow

Production lab:

```text
C:\Lab_Win11
```

GitHub publishing copy:

```text
F:\Aplicatii\Lab_Win11\GitHub
```

Run this before committing:

```text
Sync-GitHub-Lab.cmd
```
'@
[System.IO.File]::WriteAllText((Join-Path $PublishRoot "README.md"), $readme, [System.Text.UTF8Encoding]::new($false))

Write-Section "Done"
Write-Host "Now open this folder in GitHub Desktop:"
Write-Host "  $PublishRoot"
Write-Host ""
Write-Host "Review changes, commit, and push."
